### ISSUE TITLE
{openapi:genDeprecatedModelAttr(package,} not found

### ISSUE THREAD

**Issue by boun** [quarkiverse/quarkus-openapi-generator#69]
Hi,

I am unable to generate a client in my project for Quarkus 2.5.3.Final. I am using Java 11 on an arm64 mac. Do you have any idea, why this is happening?

Thanks for your project!
boun

```
Caused by: io.quarkus.qute.TemplateException: Parser error on line 35: invalid virtual method in {openapi:genDeprecatedModelAttr(package,}
        at io.quarkus.qute.Parser.parserError(Parser.java:508)
        at io.quarkus.qute.Expressions.parseVirtualMethodParams(Expressions.java:40)
        at io.quarkus.qute.Parser.createPart(Parser.java:787)
        at io.quarkus.qute.Parser.parseExpression(Parser.java:770)
        at io.quarkus.qute.Parser.apply(Parser.java:843)
        at io.quarkus.qute.Parser.apply(Parser.java:34)
        at io.quarkus.qute.SectionBlock$Builder.addExpression(SectionBlock.java:168)
        at io.quarkus.qute.IfSectionHelper$Factory.addExpressions(IfSectionHelper.java:122)
        at io.quarkus.qute.IfSectionHelper$Factory.addExpressions(IfSectionHelper.java:124)
        at io.quarkus.qute.IfSectionHelper$Factory.initializeBlock(IfSectionHelper.java:112)
        at io.quarkus.qute.Parser.flushTag(Parser.java:434)
        at io.quarkus.qute.Parser.tag(Parser.java:295)
        at io.quarkus.qute.Parser.processCharacter(Parser.java:202)
        at io.quarkus.qute.Parser.parse(Parser.java:134)
        at io.quarkus.qute.EngineImpl.parse(EngineImpl.java:56)
        at io.quarkus.qute.Engine.parse(Engine.java:30)
        at io.quarkiverse.openapi.generator.deployment.template.QuteTemplatingEngineAdapter.cacheTemplates(QuteTemplatingEngineAdapter.java:71)
        at io.quarkiverse.openapi.generator.deployment.template.QuteTemplatingEngineAdapter.compileTemplate(QuteTemplatingEngineAdapter.java:58)
        at org.openapitools.codegen.TemplateManager.write(TemplateManager.java:163)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1034)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1021)
        at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:388)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:523)
        ... 132 more
```

**Comment by ricardozanini** [comment]
> I am unable to generate a client in my project for Quarkus 2.5.3.Final

Also, can you upgrade to Quarkus 2.8.x?

**Comment by ricardozanini** [comment]
@boun I've merged the PR. Can you try building the project locally and use it in your project to see if it fixes this problem? Or can you provide me with a reproducer?

**Comment by ricardozanini** [comment]
@antssilva96, is this the bug were you seeing?

**Comment by boun** [comment]
thanks for your prompt reply. I checked with 0.6.1 but it did not fix the problem. _However_ upgrading Quarkus to 2.8 did it! Thanks so much and sorry for the noise!
