### ISSUE TITLE
Release workflow is not working

### ISSUE THREAD

**Issue by hbelmiro** [quarkiverse/quarkus-openapi-generator#752]
The latest release wasn't completed successfully.
See: https://github.com/quarkiverse/quarkus-openapi-generator/actions/runs/9959114713/job/27523391547

**Comment by hbelmiro** [comment]
@ricardozanini @mcruzdev @fjtirado would any of you guys have the bandwidth to look into this? I'm quite busy for now.

**Comment by mcruzdev** [comment]
I can do this

**Comment by ricardozanini** [comment]
@mcruzdev ping me on Zulip if you need help.

**Comment by mcruzdev** [comment]
Probably I will have time to do this one at night

**Comment by hungchu0912** [comment]
Hello guys, not much related to this, i am playing around with server generator and looking at the reactive configuration, seems like it only available on 3.0.0-SNAPSHOT which requires local build. May i know when will be the plan for 3.0.0 version release published? Many thanks in advance

**Comment by hbelmiro** [comment]
@hungchu0912 it will be available in the next release as soon as we fix it.

**Comment by hbelmiro** [comment]
@mcruzdev the release is still failing after your fix. Can you take a second look?
https://github.com/quarkiverse/quarkus-openapi-generator/actions/runs/10267122592/job/28406928335

**Comment by ricardozanini** [comment]
@hbelmiro it seems our token as expired or is invalid:
```
2024-08-06T13:18:41.2717327Z [INFO] [ERROR] Remote staging finished with a failure: Failed to deploy artifacts: Could not transfer artifact io.quarkiverse.openapi.generator:quarkus-openapi-generator-deployment:jar.asc:2.4.4 from/to ossrh (https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioquarkiverse-3049): authentication failed for https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioquarkiverse-3049/io/quarkiverse/openapi/generator/quarkus-openapi-generator-deployment/2.4.4/quarkus-openapi-generator-deployment-2.4.4.jar.asc, status: 401 Content access is protected by token
```

@gastaldi do you know if something changes in the Quarkus release CI?

**Comment by gastaldi** [comment]
@ricardozanini the release workflow changed some time ago, I have created some PRs migrating, but it appears that some repositories were missing. 

https://github.com/quarkiverse/quarkus-openapi-generator/pull/757 should fix it

**Comment by hbelmiro** [comment]
Still failing...
```
fatal: ambiguous argument 'docs/modules/ROOT/pages/includes/attributes.adoc': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: pathspec 'docs/modules/ROOT/pages/includes/attributes.adoc' did not match any files
Error: Process completed with exit code 128.
```
https://github.com/quarkiverse/quarkus-openapi-generator/actions/runs/10273287271/job/28427408231

Seems related to @mcruzdev changes.

**Comment by ricardozanini** [comment]
> Seems related to @mcruzdev changes.

oh noes! 😆 

@mcruzdev can you please take a look? At least the permissions problem have been solved by @gastaldi 🙏

**Comment by ricardozanini** [comment]
@hbelmiro shouldn't we keep this one opened?

**Comment by mcruzdev** [comment]
Sorry for delay, I was out today... but happy that the was solved!

**Comment by hbelmiro** [comment]
> @hbelmiro shouldn't we keep this one opened?

@gastaldi just sent a fix: https://github.com/quarkiverse/quarkus-openapi-generator/pull/759 🤞🏽

**Comment by ricardozanini** [comment]
I have to pay a beer to @gastaldi some day.

**Comment by gastaldi** [comment]
@ricardozanini noted 😉

**Comment by hbelmiro** [comment]
https://github.com/quarkiverse/quarkus-openapi-generator/actions/runs/10274149171/job/28430223597

![image](https://github.com/user-attachments/assets/2b5c9659-ab87-4a65-8248-65ab4773126f)

You guys rock!! Thank you @gastaldi @mcruzdev @ricardozanini
